### ISSUE TITLE
Breaking changes not documented

### ISSUE THREAD

**Issue by jocubeit** [ilap/pinenacl-dart#12]
We no longer have access to `SigningKey` from `package:pinenacl/api.dart`.

How do we now access this class?

**Comment by ilap** [comment]
Hi,

Sorry I have refactored it for about 5 months ago, using it's own api.
Use `import 'package:pinenacl/ed25519.dart';`
instead 

Cheers,

Pal

**Comment by jocubeit** [comment]
Thanks.
