### ISSUE TITLE
SigningKey doesn't roundtrip

### ISSUE THREAD

**Issue by mernen** [ilap/pinenacl-dart#17]
`SigningKey.encode()` seems to be correctly encoding the secret key (64 bytes), but the decoder is indirectly using the `fromSeed()` constructor, which expects 32 bytes. Sample code:

```dart
var key = SigningKey.generate();
var encoded = key.encode();
var decoded = SigningKey.decode(encoded);
assert(key == decoded);
```

Expected: `key` and `decoded` are equivalent

Actual:

    Unhandled exception:
    Exception: SigningKey must be created from a 32 byte seed
    #0      SigningKey._seedToSecret (package:pinenacl/src/signatures/ed25519.dart:113:7)
    #1      new SigningKey.fromSeed (package:pinenacl/src/signatures/ed25519.dart:83:29)
    #2      new SigningKey (package:pinenacl/src/signatures/ed25519.dart:76:48)
    #3      new SigningKey.decode (package:pinenacl/src/signatures/ed25519.dart:89:9)
    #4      main (file:///Users/daniel/Dev/pinenacl_poc/bin/pinenacl_poc.dart:6:28)
    #5      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:295:32)
    #6      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)

**Comment by mernen** [comment]
Looking into this, it seems [PyNaCl only encodes the seed](https://github.com/pyca/pynacl/blob/b7232f82b54ee777ebe0840ef235b7c845d811ea/src/nacl/signing.py#L194-L195), which is technically fine for Curve25519 since its secret is in fact only 32 bytes, but NaCl declares `crypto_sign_SECRETKEYBYTES` to be 64, so it seems to me one should follow that and always treat the secret as the full 64 bytes, rather than relying on the implementation detail that the other half of the key can be reconstructed.

For comparison, other implementations, like [tweetnacl.c](https://tweetnacl.cr.yp.to/20140427/tweetnacl.c) and [TweetNaCl.js](https://github.com/dchest/tweetnacl-js) don't really have the concept of serialization/deserialization, but they also don't offer API for reducing the 64-byte secret key down to a 32-byte seed, so one's only clear persistence path is to store the entire secret key.

**Comment by ilap** [comment]
Hi Daniel,

I am sorry for the confusion, but an Ed25519 key must be generated only from a 32-byte seed.
Unfortunately, the SingingKey's decoder in the code is defaulting to the `Bech32Coder`, which is wrong and it should be `HexEncoder.instance`.

To be clear:
1. An Ed25519 Signing key must be generated from a 32-byte seed which will result a valid 64-byte Ed25519 Signing key.
2. The resulted key's private key part of the signing key is **NOT** equal to the seed it comes from. As it's hashed and pruned.
3. If you want generate a SigningKey from a 64-byte priv/pub key pair from a SigningKey, then you must use the fromValid bytes as it assumes that the bytes are valid (priv key part is pruned i.e., bits are set etc.) etc.

Cheers,

Pal

**Comment by ilap** [comment]
But, I think you are right. As decoding should be done from encoded SigningKey for converting keys to/from Bech32.
Fixed now.
