### ISSUE TITLE
ByteList.fromList replacements

### ISSUE THREAD

**Issue by danbeechbloom** [ilap/pinenacl-dart#21]
Hey,

I was using the following implementation of `ByteList.fromList` with `pinenacl: 0.4.2`:
```
ByteList.fromList(
        base64.decode(encodedString),
      ),
```

 I want to upgrade to `0.6.0` but when I try to use this I get errors & can't supply a base64 decoder as the `coder` param:
 ```
 ByteList.decode(encodedString);
 ```
 
 Any tips on how to get this to work?
 
 Thanks 👍

**Comment by ilap** [comment]
Hi,

Sorry, but you need to implement the Encoder interface here: https://github.com/ilap/pinenacl-dart/blob/9a1e440feb909d485e10edc8d5417ae02a441c81/lib/api/encoding.dart#L4

It's relative simple.

**Comment by danbeechbloom** [comment]
Perfect, thanks for your help 🙌
