### ISSUE TITLE
Method UnmodifiableUint8ListView not found on Windows

### ISSUE THREAD

**Issue by Adamv27** [ilap/pinenacl-dart#22]
Attempting to build to Windows using Flutter. I'm getting 
```error G311314CC: Method not found: 'UnmodifiableUint8ListView'.```  
from ```pinenacl-0.5.1/lib/api/api.dart(90,12)```
What could be causing this?

**Comment by ilap** [comment]
Hi, 

You should try the pinenacl v0.6.0 instead the outdated v0.5.1. 

Cheers

Pal
