### ISSUE TITLE
Second constructor for EncryptedMessage

### ISSUE THREAD

**Issue by marcelgarus** [ilap/pinenacl-dart#3]
Hi 😄 
I'm using your package and it's been fun so far.
I'm doing a networking application, where `Uint8List`s are sent back and forth, containing data encrypted by your `SecretBox`.
Because `EncryptedMessage` extends `ByteList`, which in turn implements `Uint8List`, it's really easy to encrypt data and send it. On the other side though, some boilerplate is necessary to convert a received `Uint8List` to an `EncryptedMessage` in order to decrypt it.
That means, I manually have to do the following, which seems hacky because I need to know the underlying implementation details of the `EncryptedMessage`:
```
final encrypted = EncryptedMessage(
  nonce: encryptedBytes.sublist(0, TweetNaCl.nonceLength),
  cipherText: encryptedBytes.sublist(TweetNaCl.nonceLength),
);
return SecretBox(key).decrypt(encrypted);
```

It would be really helpful if `EncryptedMessage` had a constructor that simply took a `Uint8List`.

**Comment by ilap** [comment]
Hi,

Glad to hear that.

So, similar constructor would do, but should need some checks before apply.
``` dart
  EncryptedMessage.fromList({List<int> list})
      : super.fromList(list, nonceLength /* nonceLength as min length */);
```

**Comment by ilap** [comment]
Fixed and package also [uploaded](https://pub.dev/packages/pinenacl/versions/0.1.3-dev.1).
So use  the v0.1.3.-dev.1 one.

Cheers
